language: bash
os: osx
osx_image: xcode8.3

install:
- brew update && brew install shellcheck
- mkdir /tmp/dotfiles-master/
- cp -R . /tmp/dotfiles-master/

script:
 - travis_wait 30 brew upgrade boost
 - bash install.sh $CI_PART

env:
  - CI_PART=0
  - CI_PART=1
  - CI_PART=2
  - CI_PART=3
  - CI_PART=4
  - CI_PART=5
  - CI_PART=6
