export EDITOR="nvim"
export PAGER="bat"
export MANPAGER='nvim +Man!'
export WORDCHARS="*?_-.[]~=/&;!#$%^(){}<>"
export ZSH_COMPDUMP="${ZDOTDIR:-${ZSH}}/cache/.zcompdump-${SHORT_HOST}-${ZSH_VERSION}"

export path=("$HOME/.local/bin" $path)
export IDF_CCACHE_ENABLE=1
export MENUCONFIG_STYLE="default"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# load p10k from brew
ZSH_THEME=""

HYPHEN_INSENSITIVE="true"

COMPLETION_WAITING_DOTS=true
# DISABLE_MAGIC_FUNCTIONS=true
ENABLE_CORRECTION=true
export CORRECT_IGNORE='(ci|cu|.wrangler)'

ZSH_COMPDUMP="$ZSH_CACHE_DIR/.zcompdump-${SHORT_HOST}-${ZSH_VERSION}"

# Uncomment one of the following lines to change the auto-update behavior
zstyle ':omz:update' mode auto      # update automatically without asking

# Uncomment the following line to change how often to auto-update (in days).
zstyle ':omz:update' frequency 1

DEFAULT_USER="steven"

ZSH_THEME=""

plugins=(
  bgnotify
  colored-man-pages
  command-not-found
  common-aliases
  cp
  docker
  extract
  gh
  git
  gitfast
  gitignore
  httpie
  # iterm2
  macos
  man
  npm
  pip
  poetry
  python
  # safe-paste
  sudo
  vscode
  wd
  yarn
)

function bgnotify_formatted {
  ## $1=exit_status, $2=command, $3=elapsed_time

  # if command = "gg" or if it contains vim, then don't show notification
  if [[ $2 == "gg" ]] || [[ $2 == *"vim"* ]]; then
    sleep 5
    return
  fi

  # Humanly readable elapsed time
  local elapsed="$(( $3 % 60 ))s"
  (( $3 < 60 ))   || elapsed="$((( $3 % 3600) / 60 ))m $elapsed"
  (( $3 < 3600 )) || elapsed="$((  $3 / 3600 ))h $elapsed"

  [ $1 -eq 0 ] && title="Success!" || title="Nope..."
  # [ $1 -eq 0 ] && icon="$HOME/icons/success.png" || icon="$HOME/icons/fail.png"
  bgnotify "$title - took ${elapsed}" "$2" # "$icon"
}

# zstyle ':completion:*:*:docker:*' option-stacking yes
# zstyle ':completion:*:*:docker-*:*' option-stacking yes

# zstyle :omz:plugins:iterm2 shell-integration yes
# test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

setopt correct

source "$ZSH/oh-my-zsh.sh"


# alias ls=eza
alias l="ls -lhF"
alias la="ls -lAhF"
alias python=python3
alias pip=pip3
alias rsc="rsync -rlpEogtSzhP"
alias gcl1="git clone --depth=1"
alias glr="git pull --rebase"
alias gg="lazygit"
alias lgit="lazygit"
alias prcheck="gh pr checkout"
alias myip="curl ipv4.icanhazip.com"
alias rsc="rsync -rlpEogtSzhP"
unalias rm
alias rm="rm"
alias vim="nvim"
alias cwd="pwd"
alias q="quit"
alias cl="clear;clear"
alias ncdu="ncdu --color dark -t 4"
alias yu="yarn upgrade"
alias idf="nix shell github:mirrexagon/nixpkgs-esp-dev#esp-idf-full"
alias nnn="PAGER='bat --paging=always' nnn -e"
alias glow="glow -p"

rerun-last-command() {
  # get last command
  # this will replace current $BUFFER if set
  LBUFFER="$(fc -ln -1)"
  zle && zle redisplay
}

zle -N rerun-last-command
bindkey '^[^[^[' rerun-last-command
bindkey '^[^[^[^[' rerun-last-command

function rebuild() {
  local oldpwd="$PWD"
  cd ~/nix-config || return

  if [[ $(uname) == Darwin ]]; then
    sudo darwin-rebuild switch --flake .#mac "$@"
  else
    echo "not running on darwin, edit zshrc to support"
  fi

  cd "$oldpwd"
}

alias re=rebuild


# curl -sSL https://raw.githubusercontent.com/alacritty/alacritty/master/extra/alacritty.info | tic -x -
h=()
if [[ -r ~/.ssh/config ]]; then
  h=($h ${${${(@M)${(f)"$(cat ~/.ssh/config)"}:#Host *}#Host }:#*[*?]*})
fi
if [[ $#h -gt 0 ]]; then
  zstyle ':completion:*:ssh:*' hosts $h
  zstyle ':completion:*:slogin:*' hosts $h
fi
function gac() {
    git add --all
    git commit -v $@
}
function gacp() {
    git add --all
    git commit -v $@
    git push
}
function find_port_blocker() {
  if ! [ $# -eq 1 ]; then
    echo "Please specify the port you want to check
$ $0 [ 8000 ]"
    return 1
  fi

  lsof -i :$1
}
function clean_macos_crap() {
  rm -rf {.,_.,_.}{fseventsd,Spotlight-V*,Trashes}
  mkdir .fseventsd
  touch .fseventsd/no_log .metadata_never_index .Trashes
}
# function to call nvim and then exit the shell
function nnvim() {
  nvim $@
  exit
}

# eval "$(zellij setup --generate-completion zsh)"
# compdef zellij

# autoload -U is-at-least

# function zr () { zellij run --name "$*" -- zsh -ic "$*";}
# function zrf () { zellij run --name "$*" --floating -- zsh -ic "$*";}
# function zri () { zellij run --name "$*" --in-place -- zsh -ic "$*";}
# function ze () { zellij edit "$*";}
# function zef () { zellij edit --floating "$*";}
# function zei () { zellij edit --in-place "$*";}
# function zpipe () {
#   if [ -z "$1" ]; then
#     zellij pipe;
#   else
#     zellij pipe -p $1;
#   fi
# }

# autoload -U +X compinit && compinit
# . <( zellij setup --generate-completion zsh | sed -Ee 's/^(_(zellij) ).*/compdef \1\2/' )

# source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme

[[ "$TERM_PROGRAM" == "vscode" ]] && . "/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration-rc.zsh"
