#
# Use this configuration with WireGuard client
#
[Interface]
Address = 10.14.0.2/16
PrivateKey = REDACTED_WIREGUARD_PRIVATE_KEY
DNS = 162.252.172.57, 149.154.159.92
[Peer]
PublicKey = REDACTED_WIREGUARD_PUBLIC_KEY
AllowedIPs = 0.0.0.0/0
Endpoint = us-sjc.prod.surfshark.com:51820

